//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravlyk.SAE.Drawing.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ravlyk.SAE.Drawing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falscher Wert &apos;{0}&apos; in Spalte #{1} ({2}) für Farbe mit Code {3}. Der Wert sollte zwischen 0 und 255 liegen. ähnelt.
        /// </summary>
        internal static string ErrorIncerroctPaletteCsvValue {
            get {
                return ResourceManager.GetString("ErrorIncerroctPaletteCsvValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsches Format oder Anzahl der Werte in der CSV-Datei. Erwarte Liste von Zeichenfolgen im folgenden Format: ähnelt.
        /// </summary>
        internal static string ErrorIncorrectPaletteCsvFormat {
            get {
                return ResourceManager.GetString("ErrorIncorrectPaletteCsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farben ähnelt.
        /// </summary>
        internal static string ExcelSheetPalette {
            get {
                return ResourceManager.GetString("ExcelSheetPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage ähnelt.
        /// </summary>
        internal static string ExcelSheetScheme {
            get {
                return ResourceManager.GetString("ExcelSheetScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Bags ähnelt.
        /// </summary>
        internal static string PrintColumnBags {
            get {
                return ResourceManager.GetString("PrintColumnBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blau ähnelt.
        /// </summary>
        internal static string PrintColumnBlue {
            get {
                return ResourceManager.GetString("PrintColumnBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code ähnelt.
        /// </summary>
        internal static string PrintColumnCode {
            get {
                return ResourceManager.GetString("PrintColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ähnelt.
        /// </summary>
        internal static string PrintColumnColor {
            get {
                return ResourceManager.GetString("PrintColumnColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Steine ähnelt.
        /// </summary>
        internal static string PrintColumnCount {
            get {
                return ResourceManager.GetString("PrintColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grn ähnelt.
        /// </summary>
        internal static string PrintColumnGreen {
            get {
                return ResourceManager.GetString("PrintColumnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string PrintColumnName {
            get {
                return ResourceManager.GetString("PrintColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rot ähnelt.
        /// </summary>
        internal static string PrintColumnRed {
            get {
                return ResourceManager.GetString("PrintColumnRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite {0} von {1} ähnelt.
        /// </summary>
        internal static string PrintPageNo {
            get {
                return ResourceManager.GetString("PrintPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string PrintPagesIndex {
            get {
                return ResourceManager.GetString("PrintPagesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbpalette: {0} ähnelt.
        /// </summary>
        internal static string PrintThreadsName {
            get {
                return ResourceManager.GetString("PrintThreadsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe hinzufügen ähnelt.
        /// </summary>
        internal static string UndoRedoActionAddThread {
            get {
                return ResourceManager.GetString("UndoRedoActionAddThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zellenfarbe ändern ähnelt.
        /// </summary>
        internal static string UndoRedoActionChangeCellColor {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbsymbol ändern ähnelt.
        /// </summary>
        internal static string UndoRedoActionChangeColorSymbol {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeColorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ändern ähnelt.
        /// </summary>
        internal static string UndoRedoActionChangeThread {
            get {
                return ResourceManager.GetString("UndoRedoActionChangeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl ausschneiden ähnelt.
        /// </summary>
        internal static string UndoRedoActionCut {
            get {
                return ResourceManager.GetString("UndoRedoActionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereich füllen ähnelt.
        /// </summary>
        internal static string UndoRedoActionFillRegion {
            get {
                return ResourceManager.GetString("UndoRedoActionFillRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügen ähnelt.
        /// </summary>
        internal static string UndoRedoActionPaste {
            get {
                return ResourceManager.GetString("UndoRedoActionPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe entfernen ähnelt.
        /// </summary>
        internal static string UndoRedoActionRemoveThread {
            get {
                return ResourceManager.GetString("UndoRedoActionRemoveThread", resourceCulture);
            }
        }
    }
}
